name: C++ CI

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'README**'
      - 'LICENSE'
      - 'config/**'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'README**'
      - 'LICENSE'
      - 'config/**'

jobs:
  build:
    name: Build, install, run and uninstall
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ ubuntu-20.04, ubuntu-22.04, ubuntu-24.04 ]
    steps:
      - name: Install build requirements
        run: sudo apt-get update ; sudo apt-get install -y cmake g++ pkg-config

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Configure
        run: rm -rf build ; cmake -B build -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release

      - name: Build and install
        run: cd build && make && sudo make install

      - name: Run
        run: (sleep 4 && killall ctd)& ctd -c config/ctd.example.yaml

      - name: Uninstall
        run: cd build && sudo make uninstall
